### PR TITLE
ignore: Add configure.orig to gitignore

### PR DESCRIPTION
**Pull request by wesbland**

### CODE REVIEW

**Comment by hzhou** [comment]
Could you add some description that which step/script generates `configure.orig`?

**Comment by wesbland** [comment]
> Could you add some description that which step/script generates `configure.orig`?

My assumption is that it comes from here:

https://github.com/pmodels/hwloc/blob/00b1d2660fa8c56f42d9c9e5b839b13d21e674bc/autogen.sh#L20

**Comment by hzhou** [comment]
> 
> 
> > Could you add some description that which step/script generates `configure.orig`?
> 
> My assumption is that it comes from here:
> 
> https://github.com/pmodels/hwloc/blob/00b1d2660fa8c56f42d9c9e5b839b13d21e674bc/autogen.sh#L20

I see. Good enough for me.

**Comment by hzhou** [comment]
We need a way to mark or collect our in-house patches so they don't get lost as we upgrade modules.

**Pull request merged**
